title: TRANSMIXR Documentation
description: An overview of the technical results for the TRANSMIXR project.
theme: just-the-docs

url: https://transmixr.github.io

color_scheme: transmixr
logo: "assets/images/transmixr.png"
favicon: "assets/images/favicon.ico"
permalink: pretty

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"



