title: TRANSMIXR Documentation
description: An overview of the technical results for the TRANSMIXR project.
theme: just-the-docs

url: https://transmixr.github.io


logo: "assets/images/transmixr.png"
favicon: "assets/images/favicon.ico"
permalink: pretty




